# @baseUrl = http://115.89.138.200:8081
# @baseUrl = http://localhost:8082
@baseUrl = http://115.89.138.200:8082

@uuid = A3200007

@uuid_quote = "A3200007"

@fileStorageId = 56305


# URL 정보 가져오기
GET {{baseUrl}}/api/bizContent/info/{{uuid}} HTTP/1.1
Content-Type: application/json

###
# 자료 등록 API
POST {{baseUrl}}/api/bizContent/putContent HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="uuid"

{{uuid}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="businessMemo"

businessMemo
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="first.png"
Content-Type: image/png

< ./test_files/first.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="second.png"
Content-Type: image/png

< ./test_files/second.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="docs"; filename="testfile1.docx"

< ./test_files/testfile1.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="docs"; filename="testfile2.docx"

< ./test_files/testfile2.docx
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
#파일 미리보기(이미지, PDF 기준)
GET {{baseUrl}}/api/bizContent/preview/{{fileStorageId}} HTTP/1.1

###
#파일 다운로드
GET {{baseUrl}}/api/bizContent/download/{{fileStorageId}} HTTP/1.1

###
#파일 삭제
DELETE {{baseUrl}}/api/bizContent/deleteFile/{{uuid}}/{{fileStorageId}}


###
# 등록된 자료 가져오기
POST {{baseUrl}}/api/bizContent/contentDetail HTTP/1.1
Content-Type: application/json

{
    "uuid": {{uuid_quote}}
}

###
#로그인
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{"jikwonCode": "bb-90083", "password": ""}

###
#토큰 갱신
POST {{baseUrl}}/api/auth/refreshToken HTTP/1.1
Content-Type: application/json
Cookie: access_token=; refresh_token=;

###
#로그아웃
POST {{baseUrl}}/api/auth/logout HTTP/1.1

###
# 관리자용API, 최근 요청된 건 가져오기
GET {{baseUrl}}/api/bizContent/admin/recentRequestHistory/10 HTTP/1.1
Content-Type: application/json
Cookie: access_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiYi05MDA4MyIsInNjb3BlcyI6WyJST0xFX1VTRVIiXSwiZnVsbG5hbWUiOiLqsJXsnYDtmZQiLCJzZXEiOjcwOTQsImRpcmVjdEpvaW50Ijp0cnVlLCJpYXQiOjE2NzQwMjU3OTksImV4cCI6MTY3NDAzMjk5OX0.i2U4uk4gfZRVOVIZix5WcPHvWpO2GsxBRvi9NWmtDG071dWJMzlyJ98SStBuZS94qSXfm1pgWib-uf4BdYE61Q; refresh_token=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJiYi05MDA4MyIsInNjb3BlcyI6WyJST0xFX1JFRlJFU0hfVE9LRU4iXSwic2VxIjo3MDk0LCJkaXJlY3RKb2ludCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9tYW5hZ2VyLm9rMTE0LmtyIiwianRpIjoiMTNiNDAxODYtOTc0My00YzhkLWJiNTItNWJhMTc4OGE3M2FjIiwiaWF0IjoxNjc0MDI1Nzk5LCJleHAiOjE2NzQwODMzOTl9.Dc37S6BnhAH_gYg6d2_qVYuPqPrTHqvR8dGaAfG2t4bUf6y7c4WmaE6FvKsqqN_PsGuC9XMTqpuGaStI-eTtXA;

###
# 관리자용API, 최근 업로드된 건 가져오기
GET {{baseUrl}}/api/bizContent/admin/recentUploadHistory/10 HTTP/1.1
Content-Type: application/json
Cookie: access_token=; refresh_token=;

###
# 관리자용API, 업체 검색
POST {{baseUrl}}/api/bizContent/admin/searchCompany HTTP/1.1
Content-Type: application/json
Cookie: access_token=; refresh_token=;

{
    "topQty": 20,
    "searchText": "041-564-0001"
}
